# simple.gocd.yaml
pipelines:
  pixelated-user-agent:
    group: packaging
    materials:
      user-agent:
        git: https://github.com/pixelated/pixelated-user-agent.git
        destination: pixelated-user-agent
        branch: master
      ci-config:
        git: https://github.com/cz8s/gocd-tests.git
        destination: ci-config
        branch: master
        whitelist:
          - pixelated-user-agent.gocd.yaml
    stages:
      - build:
          clean_workspace: yes
          jobs:
            package:
              artifacts:
                - build:
                    source: pixelated-user-agent*_*.deb
                    destination: debs
                - build:
                    source: pixelated-user-agent*_*.changes
                    destination: debs
                - build:
                    source: pixelated-user-agent*_*.tar.gz
                    destination: debs
                - build:
                    source: pixelated-user-agent*_*.dsc
                    destination: debs
              tasks:
                - exec:
                    working_directory: pixelated-user-agent
                    command: /usr/bin/dpkg-buildpackage
                    arguments:
                      - -rfakeroot
                      - -uc
                      - -us

      - lint:
          clean_workspace: true
          jobs:
            lintian:
              tasks:
               - fetch:
                    pipeline: pixelated-user-agent
                    stage: build
                    job: package
                    is_file: no
                    source: debs
               - exec:
                    command: /usr/bin/lintian
                    arguments:
                      - debs/*.changes
