# simple.gocd.yaml
pipelines:
  pixpybuild:
    group: packaging
    materials:
      pixpybuild:
        git: https://github.com/pixelated/pixpybuild.git
        destination: pixpybuild
        branch: master
      ci-config:
        git: https://github.com/cz8s/gocd-tests.git
        destination: ci-config
        branch: master
        whitelist:
          - pixpybuild.gocd.yaml
    stages:
      - build:
          clean_workspace: yes
          jobs:
            package:
              artifacts:
                - build:
                    source: pixpybuild*_*.deb
                    destination: debs
                - build:
                    source: pixpybuild*_*.changes
                    destination: debs
                - build:
                    source: pixpybuild*_*.tar.gz
                    destination: debs
                - build:
                    source: pixpybuild*_*.dsc
                    destination: debs
              tasks:
                - exec:
                    command: /usr/bin/dpkg-buildpackage
                    working_directory: pixpybuild
                    arguments:
                      - -rfakeroot
                      - -uc
                      - -us

      - lint:
          clean_workspace: true
          jobs:
            lintian:
              tasks:
                - fetch:
                    pipeline: pixpybuild
                    stage: build
                    job: package
                    is_file: no
                    source: debs
                - exec:
                    working_directory: debs
                    command: ls
                    arguments:
                      - '*.changes'
